### ISSUE TITLE
[Suggestion]: Allow Volume Change in Config File

### ISSUE THREAD

**Issue by Darkosto** [Mrbysco/DailyDad#2]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Currently, there isn't a great way to lower the volume for Daily Dad without turning the master volume down. Is it possible we could have a volume setting in the config to lower it a bit? (It's quite a bit louder than everything else in the game right now for me)

Thank you! I love you <3
Darksosoto

MC: 1.18.2
Forge: 40.1.71
DailyDad: 1.3.2

**Comment by Mrbysco** [comment]
I've looked into it but the Text2Speech library mojang made/uses doesn't have any way of changing the volume

**Comment by Darkosto** [comment]
That is sad. Feelsbad
