### ISSUE TITLE
[Suggestion]: 1.20.1 Version?

### ISSUE THREAD

**Issue by WimpieRatte** [Mrbysco/DailyDad#3]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

Since most 1.20 mods and modpacks focus on Minecraft 1.20.1, would it be possible to publish a Daily Dad version for 1.20.1?

**Comment by Mrbysco** [comment]
There already is a 1.20.1 build, it's been around for half a year 
https://www.curseforge.com/minecraft/mc-mods/daily-dad/files/all?page=1&pageSize=20&version=1.20.1

**Comment by WimpieRatte** [comment]
Thanks!
On Modrinth it still only shows 1.20 and 1.20.2-1.20.4 compatible and so when searching for your mod through Prismlauncher, I had no results.
(I didn't expect Curseforge to show a 1.20.1 compatibility, so I didn't check there.)

**Comment by Mrbysco** [comment]
I guess I forgot to update the 1.20 builds on Modrinth to mark them 1.20.1 compatible. My bad

**Comment by WimpieRatte** [comment]
My bad too - I didn't think of testing the 1.20 version. (I think because of having faced so many mods already where the 1.20 version didn't work on 1.20.1.)
